### ISSUE TITLE
Validate Links

### ISSUE THREAD

**Issue by ReadmeCritic** [uraimo/Awesome-Swift-Playgrounds#1]
Hello, I wrote a tool that can validate README links (valid URLs, not duplicate). It can be run when someone submits a pull request or when a commit is pushed to the repo.

 It is currently being used by many projects including
- https://github.com/vinta/awesome-python
- https://github.com/prakhar1989/awesome-courses
- https://github.com/ripienaar/free-for-dev
- https://github.com/vsouza/awesome-ios
- https://github.com/caesar0301/awesome-public-datasets

Examples 
- https://travis-ci.org/vinta/awesome-python/builds/98201707 ok ✅
- https://travis-ci.org/matteocrippa/awesome-swift/builds/96722421 link redirected / rename 🔴
- https://travis-ci.org/dkhamsing/open-source-ios-apps/builds/96763135 bad link / project deleted 🔴
- https://travis-ci.org/dkhamsing/open-source-ios-apps/builds/95754715 dupe 🔴

If you are interested, connect this repo to https://travis-ci.org/ and add a [`.travis.yml`](https://github.com/dkhamsing/open-source-ios-apps/blob/master/.travis.yml) file to the project. 

See https://github.com/dkhamsing/awesome_bot for options, more information 
Feel free to leave a comment :smile:

**Comment by uraimo** [comment]
I'm already using it :smile: 

Thanks for building it, really useful.

**Comment by ReadmeCritic** [comment]
:tada:

**Comment by ReadmeCritic** [comment]
hi @uraimo 
was this disabled? just wondering

**Comment by uraimo** [comment]
Hmm, no it's still on but I did remove travis from the authorized apps and it looks like travis can't send notifications anymore.
