### ISSUE TITLE
Add playgrounds as submodules

### ISSUE THREAD

**Issue by jegnux** [uraimo/Awesome-Swift-Playgrounds#12]
Wouldn't be great to add all these playgrounds as submodules so one can clone them all in once thanks to `git clone --recursive` on this repo ?

**Comment by uraimo** [comment]
Yes, I like the idea. We could put them in a playgrounds/ directory and add a few lines in the README explaining how to clone them (via --recursive or "git submodule update --init").

The current list would remain, to keep driving traffic to other repos (the actual raison d'etre of this list), but for those who want to seriously check them all out this would be a major improvement.
